### ISSUE TITLE
Fix PHP fatal error:  Uncaught TypeError

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#143]
A PHP fatal error is thrown if playing `g4` after the following sequence of moves has been played:

```
1.e4 e5 2.Nf3 Nc6 3.Bc4 h6 4.h4 g5 5.hxg5 hxg5 6.Rxh8 Bg7 7.d3 Bxh8 8.Qe2 Ng8e7 9.c3
```

![figure-02](https://user-images.githubusercontent.com/4062000/143299187-c8497ce7-aa29-4ed8-9654-ad47a9164410.png)

```
$ php cli/ws-server.php 
Welcome to PHP Chess Server
Commands available:
/accept {"id":"id"} Accepts a friend request to play a game.
/ascii Prints the ASCII representation of the game.
/castling Gets the castling status.
/captures Gets the pieces captured by both players.
/draw {"action":["accept","decline","propose"]} Allows to offer a draw.
/events Gets the events taking place on the game.
/fen Prints the FEN string representation of the game.
/heuristicpicture Takes a balanced heuristic picture of the current game.
/history The current game's history.
/ischeck Finds out if the game is in check.
/ismate Finds out if the game is over.
/piece {"position":"string"} Gets a piece by its position on the board.
/pieces {"color":["w","b"]} Gets the pieces on the board by color.
/playfen {"fen":"string"} Plays a chess move in shortened FEN format.
/quit Quits a game.
/resign {"action":["accept"]} Allows to resign a game.
/start {"mode":["analysis","loadfen","playfriend"],"fen":"string","color":["w","b"],"min":"int"} Starts a new game.
/status The current game status.
/takeback {"action":["accept","decline","propose"]} Allows to manage a takeback.
/undomove Undoes the last move.

Listening to commands...
PHP Notice:  Trying to get property 'move' of non-object in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 606
PHP Notice:  Trying to get property 'position' of non-object in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 606
PHP Notice:  Trying to get property 'next' of non-object in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 606
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Chess\Board::getPieceByPosition() must be of the type string, null given, called in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 606 and defined in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php:361
Stack trace:
#0 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php(606): Chess\Board->getPieceByPosition()
#1 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php(815): Chess\Board->undoCastle()
#2 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php(532): Chess\Board->leavesInCheck()
#3 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php(562): Chess\Board->isLegalMove()
#4 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/FEN/AbstractStringToPgn.php(92): Chess\Board->play()
#5 /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Game.php(325): Chess\FEN in /home/standard/projects/chess-server/vendor/chesslablab/php-chess/src/Board.php on line 361
```
Happy learning and coding!

**Comment by programarivm** [comment]
Today I just added a new test in order to play the buggy sequence of moves:

```
$ vendor/bin/phpunit tests/unit/Game/PlayTest.php --filter e4_e5_Nf3_Nc6_Bc4_h6_h4_g5_hxg5_hxg5_Rxh8_Bg7_d3_Bxh8_Qe2_Nge7_c3_g4
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:01.453, Memory: 31.04 MB

There was 1 error:

1) Chess\Tests\Unit\Game\PlayTest::e4_e5_Nf3_Nc6_Bc4_h6_h4_g5_hxg5_hxg5_Rxh8_Bg7_d3_Bxh8_Qe2_Nge7_c3_g4
Trying to get property 'move' of non-object

/home/standard/projects/php-chess/src/Board.php:606
/home/standard/projects/php-chess/src/Board.php:817
/home/standard/projects/php-chess/src/Board.php:532
/home/standard/projects/php-chess/src/Board.php:562
/home/standard/projects/php-chess/src/FEN/AbstractStringToPgn.php:92
/home/standard/projects/php-chess/src/Game.php:325
/home/standard/projects/php-chess/tests/unit/Game/PlayTest.php:535

ERRORS!
Tests: 1, Assertions: 17, Errors: 1.
```

This error happens because at this moment the php library is not taking into account the fact that the opponent can take a rook before castling, in which case the castling ability gets lost. It looks like it is the exact same one as https://github.com/chesslablab/php-chess/issues/144
